-- MySQL Script generated by MySQL Workbench
-- Mon Apr  6 20:49:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bancosaulo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bancosaulo` ;

-- -----------------------------------------------------
-- Schema bancosaulo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bancosaulo` DEFAULT CHARACTER SET utf8 ;
USE `bancosaulo` ;

-- -----------------------------------------------------
-- Table `bancosaulo`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancosaulo`.`produto` ;

CREATE TABLE IF NOT EXISTS `bancosaulo`.`produto` (
  `id_prod` INT NOT NULL AUTO_INCREMENT,
  `descricao_prod` VARCHAR(45) NOT NULL,
  `saldo_prod` DECIMAL(12,2) NOT NULL,
  `unidade_prod` VARCHAR(2) NOT NULL,
  `valor_prod` DECIMAL(12,2) NOT NULL,
  PRIMARY KEY (`id_prod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancosaulo`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancosaulo`.`cliente` ;

CREATE TABLE IF NOT EXISTS `bancosaulo`.`cliente` (
  `id_cli` INT NOT NULL AUTO_INCREMENT,
  `nome_cli` VARCHAR(45) NOT NULL,
  `cpf_cli` VARCHAR(14) NOT NULL,
  `ultcomp_cli` DATETIME NULL,
  PRIMARY KEY (`id_cli`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancosaulo`.`vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancosaulo`.`vendedor` ;

CREATE TABLE IF NOT EXISTS `bancosaulo`.`vendedor` (
  `id_vend` INT NOT NULL AUTO_INCREMENT,
  `nome_vend` VARCHAR(45) NOT NULL,
  `percentual_vend` DECIMAL(3,2) NOT NULL,
  PRIMARY KEY (`id_vend`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `bancosaulo`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancosaulo`.`pedido` ;

CREATE TABLE IF NOT EXISTS `bancosaulo`.`pedido` (
  `id_ped` INT NOT NULL AUTO_INCREMENT,
  `data_ped` DATETIME NOT NULL,
  `observacao_pedido` VARCHAR(255) NULL,
  `id_cli_ped` INT NOT NULL,
  `id_vend_ped` INT NOT NULL,
  PRIMARY KEY (`id_ped`),
  CONSTRAINT `fk_pedido_cliente1`
    FOREIGN KEY (`id_cli_ped`)
    REFERENCES `bancosaulo`.`cliente` (`id_cli`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_vendedor1`
    FOREIGN KEY (`id_vend_ped`)
    REFERENCES `bancosaulo`.`vendedor` (`id_vend`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancosaulo`.`pedido_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancosaulo`.`pedido_produto` ;

CREATE TABLE IF NOT EXISTS `bancosaulo`.`pedido_produto` (
  `id_pedprod` INT NOT NULL AUTO_INCREMENT,
  `quantidade_pedprod` DECIMAL(18,2) NOT NULL,
  `valor_pedprod` DECIMAL(18,2) NOT NULL,
  `total_pedprod` VARCHAR(45) NOT NULL,
  `id_prod_pedprod` INT NOT NULL,
  `id_ped_pedprod` INT NOT NULL,
  PRIMARY KEY (`id_pedprod`),
  CONSTRAINT `fk_pedprod_produto1`
    FOREIGN KEY (`id_prod_pedprod`)
    REFERENCES `bancosaulo`.`produto` (`id_prod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidoproduto_pedido1`
    FOREIGN KEY (`id_ped_pedprod`)
    REFERENCES `bancosaulo`.`pedido` (`id_ped`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancosaulo`.`vendedor_comissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancosaulo`.`vendedor_comissao` ;

CREATE TABLE IF NOT EXISTS `bancosaulo`.`vendedor_comissao` (
  `id_vendcom` INT NOT NULL AUTO_INCREMENT,
  `percentual_vendcom` DECIMAL(3,2) NOT NULL,
  `vlrcomissao_vendcom` DECIMAL(18,2) NOT NULL,
  `id_vend_vendcom` INT NOT NULL,
  `id_ped_vendcom` INT NOT NULL,
  PRIMARY KEY (`id_vendcom`),
  CONSTRAINT `fk_vendedor_comissao_vendedor1`
    FOREIGN KEY (`id_vend_vendcom`)
    REFERENCES `bancosaulo`.`vendedor` (`id_vend`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendedor_comissao_pedido1`
    FOREIGN KEY (`id_ped_vendcom`)
    REFERENCES `bancosaulo`.`pedido` (`id_ped`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancosaulo`.`produto_movimento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bancosaulo`.`produto_movimento` ;

CREATE TABLE IF NOT EXISTS `bancosaulo`.`produto_movimento` (
  `id_prodmov` INT NOT NULL AUTO_INCREMENT,
  `tipo_prodmov` VARCHAR(1) NOT NULL,
  `data_prodmov` DATETIME NOT NULL,
  `descricao_prodmov` VARCHAR(45) NULL,
  `id_prod_prodmov` INT NOT NULL,
  PRIMARY KEY (`id_prodmov`),
  CONSTRAINT `fk_prodmov_produto`
    FOREIGN KEY (`id_prod_prodmov`)
    REFERENCES `bancosaulo`.`produto` (`id_prod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
