-- MySQL Script generated by MySQL Workbench
-- Sat Apr  4 09:48:53 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `trabalho1-Saulo-2020-1` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trabalho1-Saulo-2020-1` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `trabalho1-Saulo-2020-1` ;

-- -----------------------------------------------------
-- Table `Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cliente` (
  `Id_Cli` INT NOT NULL,
  `Nome_Cli` VARCHAR(45) NOT NULL,
  `CPF_Cli` VARCHAR(14) NOT NULL,
  `UltComp_Cli` DATE NULL,
  PRIMARY KEY (`Id_Cli`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PedProd`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PedProd` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PedProd` (
  `Id_PedProd` INT NOT NULL,
  `Qtd_PedProd` DECIMAL(18,2) NOT NULL,
  `Valor_PedProd` DECIMAL(18,2) NOT NULL,
  `VTotal_PedProd` DECIMAL(18,2) NOT NULL,
  `id_prod_PedProd` INT NOT NULL,
  `id_ped_PedProd` INT NOT NULL,
  PRIMARY KEY (`Id_PedProd`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Pededido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pededido` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Pededido` (
  `Id_Ped` INT NOT NULL,
  `Data_Ped` DATETIME NOT NULL,
  `obs_Ped` VARCHAR(255) NOT NULL,
  `Id_Ved_Ped` INT NOT NULL,
  `Id_Cli_Ped` INT NOT NULL,
  PRIMARY KEY (`Id_Ped`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ProdMov`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ProdMov` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ProdMov` (
  `Id_ProdMov` INT NOT NULL AUTO_INCREMENT,
  `Tipo_ProdMov` VARCHAR(1) NOT NULL,
  `Data_ProdMov` DATETIME NOT NULL,
  `Descricao_ProdMov` VARCHAR(45) NULL,
  `IdProd_ProdMov` INT NOT NULL,
  PRIMARY KEY (`Id_ProdMov`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Produto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Produto` (
  `Id_Prod` INT NOT NULL,
  `Descricao_Prod` VARCHAR(45) NOT NULL,
  `Saldo_Prod` DECIMAL(12,2) NOT NULL,
  `Unidade_Prod` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`Id_Prod`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `VedCom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `VedCom` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `VedCom` (
  `Id_VedCom` INT NOT NULL,
  `Percentual_VedCom` DECIMAL(3,2) NOT NULL,
  `Valor_VedCom` DECIMAL(18,2) NOT NULL,
  `Id_Ped_VedCom` INT NOT NULL,
  `Id_Ved_VedCom` INT NOT NULL,
  PRIMARY KEY (`Id_VedCom`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Vedendor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Vedendor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Vedendor` (
  `Id_Ved` INT NOT NULL,
  `Nome_Ved` VARCHAR(45) NOT NULL,
  `Percentual_Ved` DECIMAL(3,2) NOT NULL,
  PRIMARY KEY (`Id_Ved`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
