-- MySQL Script generated by MySQL Workbench
-- Sat Apr  4 09:48:53 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema trabalho1-Saulo-2020-1
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `trabalho1-Saulo-2020-1` ;

-- -----------------------------------------------------
-- Schema trabalho1-Saulo-2020-1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trabalho1-Saulo-2020-1` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `trabalho1-Saulo-2020-1`;


-- -----------------------------------------------------
-- Table `Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Cliente` (
  `Id_Cli` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `Nome_Cli` VARCHAR(45) NOT NULL,
  `CPF_Cli` VARCHAR(14) NOT NULL,
  `UltComp_Cli` DATE
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Produto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Produto` (
  `Id_Prod` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `Descricao_Prod` VARCHAR(45) NOT NULL,
  `Saldo_Prod` DECIMAL(12,2) NOT NULL,
  `Unidade_Prod` VARCHAR(2) NOT NULL
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Vendedor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Vendedor` (
  `Id_Vend` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `Nome_Vend` VARCHAR(45) NOT NULL,
  `Percentual_Vend` DECIMAL(3,2) NOT NULL
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PRODUTO_MOVIMENTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PRODUTO_MOVIMENTO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PRODUTO_MOVIMENTO` (
  `Id_ProdMov` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
  `Tipo_ProdMov` VARCHAR(1) NOT NULL,
  `Data_ProdMov` DATETIME NOT NULL,
  `Descricao_ProdMov` VARCHAR(45) NULL,
  `IdProd_ProdMov` INT NOT NULL,

  CONSTRAINT FK_Produto FOREIGN KEY (IdProd_ProdMov) REFERENCES Produto(Id_Prod)

ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Vendedor_Comissao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Vendedor_Comissao` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Vendedor_Comissao` (
  `Id_VendCom` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `Percentual_VendCom` DECIMAL(3,2) NOT NULL,
  `Valor_VendCom` DECIMAL(18,2) NOT NULL,
  `Id_Ped_VendCom` INT NOT NULL,
  `Id_Vend_VendCom` INT NOT NULL,

  CONSTRAINT FK_Vend FOREIGN KEY (Id_Vend) REFERENCES TBL_VENDEDOR(Id_Vend_VendCom),
  CONSTRAINT FK_Ped FOREIGN KEY (Id_Ped) REFERENCES TBL_PEDIDO(Id_Ped_VendCom)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pedido` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Pedido` (
  `Id_Ped` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `Data_Ped` DATETIME NOT NULL,
  `obs_Ped` VARCHAR(255) NOT NULL,
  `Id_Ved_Ped` INT NOT NULL,
  `Id_Cli_Ped` INT NOT NULL,
  
  
ENGINE = InnoDB;

SHOW WARNINGS;